---
dependency:
  enabled: false
driver:
  name: delegated
  options:
    managed: false
    ansible_connection_options:
      ansible_connection: local
lint: |
  set -e
  yamllint -c .yamllint .
  ansible-lint --exclude molecule/ --exclude library/ --exclude .github/
  flake8 --exclude roles,molecule,library
provisioner:
  name: ansible
  options:
    become: true
    extra-vars: "{'testing': true, domain: 'anarres.local'}"
scenario:
  name: default
verifier:
  name: testinfra
  options:
    sudo: true
