---

- name: install base packages
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - curl
    - tree
    - htop
    - less
    - speedtest-cli
    - nload
    - git
    - vim
    - tmux
    - sendxmpp
    - mlocate
    - python-pip
    - lsof
    - python-mysqldb
    - python-pexpect
    - net-tools

- name: create sendxmpp config file
  template:
    src: sendxmpp.j2
    dest: "{{ sendxmpp_config }}"

- name: create data directory if it doesn't exists
  file:
    path: /data
    state: directory
    mode: 0700

- name: import ntp tasks
  import_tasks: ntp.yml
  tags: ntp
- name: import docker tasks
  import_tasks: docker.yml
  tags: docker
